medicamento:
    path:     /
    defaults: { _controller: "AsiClinicaBundle:Medicamento:index" }

medicamento_show:
    path:     /{id}/show
    defaults: { _controller: "AsiClinicaBundle:Medicamento:show" }

medicamento_new:
    path:     /new
    defaults: { _controller: "AsiClinicaBundle:Medicamento:new" }

medicamento_create:
    path:     /create
    defaults: { _controller: "AsiClinicaBundle:Medicamento:create" }
    requirements: { _method: post }

medicamento_edit:
    path:     /{id}/edit
    defaults: { _controller: "AsiClinicaBundle:Medicamento:edit" }

medicamento_update:
    path:     /{id}/update
    defaults: { _controller: "AsiClinicaBundle:Medicamento:update" }
    requirements: { _method: post|put }

medicamento_delete:
    path:     /{id}/delete
    defaults: { _controller: "AsiClinicaBundle:Medicamento:delete" }
    requirements: { _method: post|delete }
