municipio:
    path:     /
    defaults: { _controller: "AsiClinicaBundle:Municipio:index" }

municipio_show:
    path:     /{id}/show
    defaults: { _controller: "AsiClinicaBundle:Municipio:show" }

municipio_new:
    path:     /new
    defaults: { _controller: "AsiClinicaBundle:Municipio:new" }

municipio_create:
    path:     /create
    defaults: { _controller: "AsiClinicaBundle:Municipio:create" }
    requirements: { _method: post }

municipio_edit:
    path:     /{id}/edit
    defaults: { _controller: "AsiClinicaBundle:Municipio:edit" }

municipio_update:
    path:     /{id}/update
    defaults: { _controller: "AsiClinicaBundle:Municipio:update" }
    requirements: { _method: post|put }

municipio_delete:
    path:     /{id}/delete
    defaults: { _controller: "AsiClinicaBundle:Municipio:delete" }
    requirements: { _method: post|delete }