Asi\ClinicaBundle\Entity\Cita:
    properties:
        comentario:
            - Length:
                min: 2 
                max: 100
        estado:
            - NotBlank: ~
            - Length:
                min: 2
                max: 10
        tipocita:
            - NotBlank: ~
            - Length:
                min: 2
                max: 50

Asi\ClinicaBundle\Entity\Clinica:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nombre
    properties:
        nombre:
            - NotBlank: ~
            - Length:
                min: 4
                max: 50
        direccion:
            - NotBlank: ~
            - Length:
                min: 4
                max: 100
        telefono:
            - Length:
                min: 8
                max: 15
            - Regex: 
                pattern: '/[0-9]*/'
                message: El campo telefono debe de ser numerico.
        citahorapromedio:
            - Time: ~

Asi\ClinicaBundle\Entity\Consulta:
    properties:
        motivoconsulta:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 150
        diagnostico:
            - NotBlank: ~
            - Length:
                min: 2
                max: 300
        sintomas:
            - NotBlank: ~

Asi\ClinicaBundle\Entity\Departamento:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nombre
    properties:
        nombre:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 50

Asi\ClinicaBundle\Entity\Detallefactura:
    properties:
        precio:
            - Length:
                min: 2
                max: 10
            - Regex: 
                pattern: '/[0-9]*/'
                message: El campo precio debe de ser numerico.
        comentario:
            - Length:
                min: 2
                max: 50

Asi\ClinicaBundle\Entity\Encargado:
    properties:
        nombres:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 50
        apellidos:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 50
        telefono:
            - Length:
                min: 8
                max: 15
            - Regex: 
                pattern: '/[0-9]*/'
                message: El campo telefono debe de ser numerico.
        movil:
            - Length:
                min: 8
                max: 15
            - Regex: 
                pattern: '/[0-9]*/'
                message: El campo movil debe de ser numerico.
        direccion:
            - Length:
                min: 2 
                max: 100

Asi\ClinicaBundle\Entity\Encargadopaciente:
    properties:
        parentesco:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 15

Asi\ClinicaBundle\Entity\Especialidad:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nombre
    properties:
        nombre:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 50
        abreviatura:
            - Length:
                min: 2 
                max: 8

Asi\ClinicaBundle\Entity\Factura:
    properties:
        titular:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 100
        dui:
            - NotBlank: ~
            - Length:
                min: 9 
                max: 10
        nit:
            - NotBlank: ~
            - Length:
                min: 17 
                max: 18

Asi\ClinicaBundle\Entity\Itemexamenfisico:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nombre
    properties:
        nombre:
            - NotBlank: ~
            - Regex:
                pattern: '/^\S+\w{8,32}\S{1,}/'
                message: El nombre no debe tener espacios o caracteres especiales.
            - Length:
                min: 2 
                max: 50
        tipodato:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 45

Asi\ClinicaBundle\Entity\Log:
    properties:
        accion:
            - NotBlank: ~
            - Length:
                min: 1 
                max: 30

Asi\ClinicaBundle\Entity\Medicamento:
    properties:
        descripcion:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 100

Asi\ClinicaBundle\Entity\Medico:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: jvpm
    properties:
        jvpm:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 200
        hospitalresidente:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 50

Asi\ClinicaBundle\Entity\Paciente:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: dui
    properties:
        dui:
            - Length:
                min: 9 
                max: 10
        nombres:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 50
        apellidos:
            - NotBlank: ~
            - Length:
                min: 2 
                max: 50
        telefono:
            - Length:
                min: 8
                max: 15
            - Regex: 
                pattern: '/[0-9]*/'
                message: El campo telefono debe de ser numerico.
        movil:
            - Length:
                min: 8
                max: 15
            - Regex: 
                pattern: '/[0-9]*/'
                message: El campo telefono debe de ser numerico.
        referidopor:
            - Length:
                min: 2 
                max: 50
        lugarnacimiento:
            - Length:
                min: 2 
                max: 50
        direccion:
            - Length:
                min: 2 
                max: 50

Asi\ClinicaBundle\Entity\Pantalla:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: dirpantalla
    properties:
        nombre:
            - NotBlank: ~
            - Length:
                min: 4
                max: 50
        descripcion:
            - Length:
                min: 4
                max: 100
        dirpantalla:
            - NotBlank: ~
            - Length:
                min: 4
                max: 100

Asi\ClinicaBundle\Entity\Patologia:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nombre
    properties:
        nombre:
            - NotBlank: ~
            - Length:
                min: 4
                max: 50
        descripcion:
            - Length:
                min: 4
                max: 100

Asi\ClinicaBundle\Entity\Pednacimientodesarrollo:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: idpaciente
    properties:
        edadgestacional:
            - Length:
                min: 4
                max: 45
        condicionnacimiento:
            - Length:
                min: 4
                max: 45
        cianosis:
            - Length:
                min: 4
                max: 45
        convulsiones:
            - Length:
                min: 4
                max: 45
        ictericia:
            - Length:
                min: 4
                max: 45
        partocomentario:
            - Length:
                min: 4
                max: 45
        pesonacimiento:
            - Length:
                min: 4
                max: 45
        alimentacion:
            - Length:
                min: 4
                max: 45
        sesento:
            - Length:
                min: 4
                max: 45
        camino:
            - Length:
                min: 4
                max: 45
        separo:
            - Length:
                min: 4
                max: 45
        primeraspalabras:
            - Length:
                min: 4
                max: 45
        primerdiente:
            - Length:
                min: 4
                max: 45
        frasescortas:
            - Length:
                min: 4
                max: 45
        controlintestinal:
            - Length:
                min: 4
                max: 45
        obstetra:
            - Length:
                min: 4
                max: 45

Asi\ClinicaBundle\Entity\Medico:     
    constraints:         
        -Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: idpersonal
