Asi\ClinicaBundle\Entity\Encargado:
    type: entity
    table: encargado
    indexes:
        id_encargado_municipio1_idx:
            columns:
                - idMunicipio
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombres:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        apellidos:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        telefono:
            type: string
            nullable: true
            length: 15
            fixed: false
            comment: ''
        movil:
            type: string
            nullable: true
            length: 15
            fixed: false
            comment: ''
        fechanacimiento:
            type: date
            nullable: true
            comment: ''
            column: fechaNacimiento
        direccion:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        estadoactivacion:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: estadoActivacion
    manyToOne:
        idmunicipio:
            targetEntity: Municipio
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idMunicipio:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        encargadopaciente:
            targetEntity: Encargadopaciente
            mappedBy: idencargado
    lifecycleCallbacks: {  }
