Asi\ClinicaBundle\Entity\Factura:
    type: entity
    table: factura
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titular:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        dui:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
        nit:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
        fechahoraemision:
            type: datetime
            nullable: false
            comment: ''
            column: fechaHoraEmision
    oneToMany:
        detallefactura:
            targetEntity: Detallefactura
            mappedBy: idfactura
    oneToOne:
        idconsulta:
            targetEntity: Consulta
            mappedBy: idfactura
    lifecycleCallbacks: {  }
