Asi\ClinicaBundle\Entity\Itemexamenfisico:
    type: entity
    table: itemExamenFisico
    repositoryClass: Asi\ClinicaBundle\Entity\ItemexamenfisicoRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        tipodato:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: tipoDato
        universal:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
        estadoactivacion:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: estadoActivacion
    lifecycleCallbacks: {  }
