Asi\ClinicaBundle\Entity\Medico:
    type: entity
    table: medico
    indexes:
        id_medico_personal1_idx:
            columns:
                - idPersonal
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        jvpm:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        hospitalresidente:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: hospitalResidente
    manyToOne:
        idpersonal:
            targetEntity: Personal
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idPersonal:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
