Asi\ClinicaBundle\Entity\Municipio:
    type: entity
    table: municipio
    indexes:
        id_municipio_departamento1_idx:
            columns:
                - idDepartamento
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
    manyToOne:
        iddepartamento:
            targetEntity: Departamento
            cascade: {  }
            mappedBy: idMunicipios
            inversedBy: null
            joinColumns:
                idDepartamento:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
