Asi\ClinicaBundle\Entity\Pantalla:
    type: entity
    table: pantalla
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        descripcion:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        dirpantalla:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: dirPantalla
        estadoactivacion:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: estadoActivacion
    oneToMany:
        pantallaAcceso:
            targetEntity: PantallaAcceso
            mappedBy: pantalla
    lifecycleCallbacks: {  }
