Asi\ClinicaBundle\Entity\Politica:
    type: entity
    table: politica
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        descripcion:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        estadoactivacion:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: estadoActivacion
    lifecycleCallbacks: {  }
